package com.brainpass.brainpass

/** One general-knowledge card. [correctIndex] points into [options]. */
data class GkCard(val prompt: String, val options: List<String>, val correctIndex: Int)

/**
 * The GK banks, one per age band (~45 each). LockUi shuffles option order at
 * display time and EnginePrefs.pickFresh avoids recently-shown cards, so kids
 * don't see repeats for a long while.
 */
object Gk {
    fun byBand(b: Band): List<GkCard> = when (b) {
        Band.A -> bandA
        Band.B -> bandB
        Band.C -> bandC
        Band.D -> bandD
    }

    private val bandA = listOf(
        GkCard("What is a baby dog called?", listOf("Puppy", "Kitten", "Cub"), 0),
        GkCard("The sun is a...?", listOf("Star", "Planet", "Cloud"), 0),
        GkCard("Which animal gives us milk?", listOf("Cow", "Lion", "Snake"), 0),
        GkCard("How many sides does a triangle have?", listOf("3", "4", "5"), 0),
        GkCard("Where do fish live?", listOf("Water", "Trees", "Sky"), 0),
        GkCard("What colour is the sky on a clear day?", listOf("Blue", "Green", "Red"), 0),
        GkCard("Which insect makes honey?", listOf("Bee", "Ant", "Spider"), 0),
        GkCard("What do we see with?", listOf("Eyes", "Ears", "Nose"), 0),
        GkCard("How many days are in a week?", listOf("7", "5", "10"), 0),
        GkCard("Ice is frozen...?", listOf("Water", "Milk", "Juice"), 0),
        GkCard("What is a baby cat called?", listOf("Kitten", "Puppy", "Calf"), 0),
        GkCard("What do plants need to grow?", listOf("Water and sunlight", "Candy", "Toys"), 0),
        GkCard("Which animal is known as the king of the jungle?", listOf("Lion", "Monkey", "Elephant"), 0),
        GkCard("Which fruit is yellow and sweet?", listOf("Banana", "Apple", "Grape"), 0),
        GkCard("How many legs does a dog have?", listOf("4", "2", "6"), 0),
        GkCard("Which is the odd one out?", listOf("Car", "Truck", "Apple"), 2),
        GkCard("What sound does a cow make?", listOf("Moo", "Meow", "Oink"), 0),
        GkCard("Which one is hot?", listOf("Fire", "Snow", "Ice cream"), 0),
        GkCard("Which one is cold?", listOf("Ice", "Soup", "Sun"), 0),
        GkCard("Which is the largest animal on land?", listOf("Elephant", "Mouse", "Rabbit"), 0),
        GkCard("Which is the odd one out?", listOf("Blue", "Red", "Square"), 2),
        GkCard("What season comes after winter?", listOf("Spring", "Autumn", "Summer"), 0),
        GkCard("Which animal hops and carries its baby in a pouch?", listOf("Kangaroo", "Koala", "Panda"), 0),
        GkCard("How many fingers do you have on one hand?", listOf("5", "10", "4"), 0),
        GkCard("Which bird can mimic human words?", listOf("Parrot", "Penguin", "Eagle"), 0),
        // -- expansion --
        GkCard("What do you wear on your feet?", listOf("Shoes", "Gloves", "Hat"), 0),
        GkCard("Which animal has a very long neck?", listOf("Giraffe", "Pig", "Goat"), 0),
        GkCard("What do chickens lay?", listOf("Eggs", "Seeds", "Stones"), 0),
        GkCard("Which one can fly?", listOf("Butterfly", "Dog", "Fish"), 0),
        GkCard("What colour is grass?", listOf("Green", "Purple", "Orange"), 0),
        GkCard("Where does a bird live?", listOf("Nest", "Kennel", "Cave"), 0),
        GkCard("Which one do we drink?", listOf("Water", "Sand", "Paper"), 0),
        GkCard("What do bees visit to collect nectar?", listOf("Flowers", "Rocks", "Cars"), 0),
        GkCard("Which animal says 'oink oink'?", listOf("Pig", "Horse", "Sheep"), 0),
        GkCard("How many wheels does a bicycle have?", listOf("2", "4", "3"), 0),
        GkCard("Which one is a vegetable?", listOf("Carrot", "Chocolate", "Biscuit"), 0),
        GkCard("What do we use an umbrella for?", listOf("Rain", "Reading", "Eating"), 0),
        GkCard("A baby cow is called a...?", listOf("Calf", "Foal", "Chick"), 0),
        GkCard("Which animal loves to eat bananas?", listOf("Monkey", "Cow", "Hen"), 0),
        GkCard("What shape is a ball?", listOf("Round", "Square", "Flat"), 0),
        GkCard("Which one shines at night?", listOf("Moon", "Chair", "Shoe"), 0),
        GkCard("The peacock is a very colourful...?", listOf("Bird", "Fish", "Insect"), 0),
        GkCard("Which one is a mango?", listOf("A fruit", "An animal", "A toy"), 0),
        GkCard("What do we brush every morning?", listOf("Teeth", "Shoes", "Walls"), 0),
        GkCard("Which animal pulls a cart in villages?", listOf("Bullock", "Tiger", "Peacock"), 0),
    )

    private val bandB = listOf(
        GkCard("Which is the fastest land animal?", listOf("Cheetah", "Elephant", "Turtle"), 0),
        GkCard("A group of lions is called a...?", listOf("Pride", "Pack", "Herd"), 0),
        GkCard("How many legs does a spider have?", listOf("8", "6", "4"), 0),
        GkCard("Water freezes at what temperature (°C)?", listOf("0", "50", "100"), 0),
        GkCard("Bats are...?", listOf("Mammals", "Birds", "Insects"), 0),
        GkCard("Which word is spelled correctly?", listOf("Elephant", "Elefant", "Elaphent"), 0),
        GkCard("What is the closest star to Earth?", listOf("The Sun", "Proxima Centauri", "Polaris"), 0),
        GkCard("Which animal is a herbivore (eats only plants)?", listOf("Rabbit", "Lion", "Wolf"), 0),
        GkCard("Which shape has 5 sides?", listOf("Pentagon", "Hexagon", "Octagon"), 0),
        GkCard("Which is the odd one out?", listOf("Carrot", "Broccoli", "Banana"), 2),
        GkCard("How many months are in a year?", listOf("12", "10", "14"), 0),
        GkCard("What gas do we breathe to stay alive?", listOf("Oxygen", "Carbon Dioxide", "Nitrogen"), 0),
        GkCard("Which ocean is the biggest on Earth?", listOf("Pacific", "Atlantic", "Indian"), 0),
        GkCard("What is the capital of the United Kingdom?", listOf("London", "Paris", "New York"), 0),
        GkCard("Which is the odd one out?", listOf("Bus", "Train", "Bicycle"), 2),
        GkCard("Which bird cannot fly?", listOf("Penguin", "Sparrow", "Robin"), 0),
        GkCard("How many colors are in a rainbow?", listOf("7", "6", "8"), 0),
        GkCard("What is the name of our galaxy?", listOf("Milky Way", "Andromeda", "Solar System"), 0),
        GkCard("Which force pulls everything down to Earth?", listOf("Gravity", "Magnetism", "Wind"), 0),
        GkCard("What do bees collect from flowers to make honey?", listOf("Nectar", "Water", "Seeds"), 0),
        GkCard("Which animal can live both in water and on land?", listOf("Frog", "Fish", "Whale"), 0),
        GkCard("What is the main ingredient of paper?", listOf("Wood", "Plastic", "Glass"), 0),
        GkCard("Which is the tallest mammal on Earth?", listOf("Giraffe", "Elephant", "Moose"), 0),
        GkCard("How many hours are in one day?", listOf("24", "12", "48"), 0),
        GkCard("I have a spine but no bones. I have leaves but no branches. What am I?", listOf("Book", "Tree", "Cactus"), 0),
        // -- expansion --
        GkCard("What is India's national bird?", listOf("Peacock", "Crow", "Pigeon"), 0),
        GkCard("What is India's national animal?", listOf("Tiger", "Lion", "Elephant"), 0),
        GkCard("Which festival is called the festival of lights?", listOf("Diwali", "Holi", "Eid"), 0),
        GkCard("Which shape has no corners?", listOf("Circle", "Square", "Triangle"), 0),
        GkCard("Caterpillars turn into...?", listOf("Butterflies", "Bees", "Birds"), 0),
        GkCard("Which planet do we live on?", listOf("Earth", "Mars", "Venus"), 0),
        GkCard("What do camels store in their humps?", listOf("Fat", "Water", "Sand"), 0),
        GkCard("Which sense do we use to hear?", listOf("Ears", "Eyes", "Tongue"), 0),
        GkCard("How many sides does a square have?", listOf("4", "3", "6"), 0),
        GkCard("Where do penguins mostly live?", listOf("Cold places", "Deserts", "Jungles"), 0),
        GkCard("Which of these is a healthy breakfast?", listOf("Fruit and milk", "Only candy", "Only chips"), 0),
        GkCard("Which vehicle runs on tracks?", listOf("Train", "Car", "Scooter"), 0),
        GkCard("The doctor who treats teeth is a...?", listOf("Dentist", "Farmer", "Pilot"), 0),
        GkCard("Which day comes after Friday?", listOf("Saturday", "Monday", "Thursday"), 0),
        GkCard("What melts in the sun?", listOf("Ice cream", "A rock", "A spoon"), 0),
        GkCard("Which one is a wild animal?", listOf("Wolf", "Cow", "Goat"), 0),
        GkCard("Turtles carry their home on their...?", listOf("Back", "Head", "Tail"), 0),
        GkCard("What is a group of fish called?", listOf("School", "Class", "Team"), 0),
        GkCard("Plants drink water through their...?", listOf("Roots", "Leaves", "Flowers"), 0),
        GkCard("Which meal do we eat in the morning?", listOf("Breakfast", "Dinner", "Supper"), 0),
    )

    private val bandC = listOf(
        GkCard("Which is the largest planet in our solar system?", listOf("Jupiter", "Earth", "Mars"), 0),
        GkCard("On which continent is the Sahara Desert?", listOf("Africa", "Asia", "Europe"), 0),
        GkCard("Roughly how many bones are in an adult human body?", listOf("206", "100", "500"), 0),
        GkCard("In which country is the Great Wall?", listOf("China", "India", "Egypt"), 0),
        GkCard("Making food from sunlight is called...?", listOf("Photosynthesis", "Digestion", "Evaporation"), 0),
        GkCard("What currency is used in Japan?", listOf("Yen", "Dollar", "Rupee"), 0),
        GkCard("Which instrument is used to measure temperature?", listOf("Thermometer", "Barometer", "Speedometer"), 0),
        GkCard("What is the hardest natural substance on Earth?", listOf("Diamond", "Gold", "Iron"), 0),
        GkCard("Which is the smallest continent by land area?", listOf("Australia", "Europe", "South America"), 0),
        GkCard("What do we call a scientist who studies stars and space?", listOf("Astronomer", "Biologist", "Geologist"), 0),
        GkCard("What is the boiling point of water (°C)?", listOf("100", "0", "50"), 0),
        GkCard("Which organ pumps blood through your body?", listOf("Heart", "Brain", "Lungs"), 0),
        GkCard("I can fill a room but take up no space. What am I?", listOf("Light", "Water", "Air"), 0),
        GkCard("If you mix blue and yellow, what color do you get?", listOf("Green", "Orange", "Purple"), 0),
        GkCard("Which country is famous for pyramids?", listOf("Egypt", "Mexico", "Greece"), 0),
        GkCard("What is the name of the long sleep animals take in winter?", listOf("Hibernation", "Migration", "Snoozing"), 0),
        GkCard("Which planet is closest to the Sun?", listOf("Mercury", "Venus", "Mars"), 0),
        GkCard("How many players are on a soccer field for one team?", listOf("11", "9", "7"), 0),
        GkCard("Which animal is the largest mammal in the world?", listOf("Blue Whale", "Elephant", "Giraffe"), 0),
        GkCard("Who was the first person to step on the Moon?", listOf("Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin"), 0),
        GkCard("What is the capital of France?", listOf("Paris", "Rome", "Berlin"), 0),
        GkCard("Which language has the most native speakers in the world?", listOf("Chinese Mandarin", "English", "Spanish"), 0),
        GkCard("What gas do plants release during photosynthesis?", listOf("Oxygen", "Carbon Dioxide", "Hydrogen"), 0),
        GkCard("I have keys but no locks. You can play me but can't enter me. What am I?", listOf("Piano", "Computer", "Door"), 0),
        GkCard("Which country is also a continent?", listOf("Australia", "India", "Brazil"), 0),
        // -- expansion --
        GkCard("What is the capital of India?", listOf("New Delhi", "Mumbai", "Kolkata"), 0),
        GkCard("Which river is considered the holiest in India?", listOf("Ganga", "Amazon", "Nile"), 0),
        GkCard("Who is known as the Father of the Indian Nation?", listOf("Mahatma Gandhi", "Nehru", "Tagore"), 0),
        GkCard("Which is the longest river in the world?", listOf("Nile", "Ganga", "Thames"), 0),
        GkCard("How many continents are there on Earth?", listOf("7", "5", "9"), 0),
        GkCard("Which vitamin do we get from sunlight?", listOf("Vitamin D", "Vitamin A", "Vitamin C"), 0),
        GkCard("The Taj Mahal is in which city?", listOf("Agra", "Jaipur", "Delhi"), 0),
        GkCard("Which sea creature has 8 arms?", listOf("Octopus", "Crab", "Starfish"), 0),
        GkCard("What does a caterpillar build around itself?", listOf("Cocoon", "Nest", "Web"), 0),
        GkCard("Which planet is called Earth's twin?", listOf("Venus", "Mars", "Pluto"), 0),
        GkCard("Sound cannot travel through...?", listOf("Empty space", "Water", "Air"), 0),
        GkCard("What is the largest island in the world?", listOf("Greenland", "Sri Lanka", "Iceland"), 0),
        GkCard("Which blood cells fight germs?", listOf("White cells", "Red cells", "Skin cells"), 0),
        GkCard("A person who writes books is called an...?", listOf("Author", "Actor", "Athlete"), 0),
        GkCard("Which gas makes balloons float up?", listOf("Helium", "Oxygen", "Steam"), 0),
        GkCard("How many minutes are in one hour?", listOf("60", "100", "30"), 0),
        GkCard("Which mountain is the tallest in the world?", listOf("Mount Everest", "K2", "Alps"), 0),
        GkCard("Spiders spin webs to...?", listOf("Catch food", "Sleep in", "Stay warm"), 0),
        GkCard("Which one is a source of light?", listOf("The Sun", "The Moon", "A mirror"), 0),
        GkCard("What do we call molten rock from a volcano?", listOf("Lava", "Mud", "Steam"), 0),
    )

    private val bandD = listOf(
        GkCard("What is the chemical symbol for gold?", listOf("Au", "Gd", "Go"), 0),
        GkCard("What is the smallest prime number?", listOf("2", "1", "3"), 0),
        GkCard("Which planet is known as the Red Planet?", listOf("Mars", "Venus", "Jupiter"), 0),
        GkCard("Which travels faster?", listOf("Light", "Sound", "They are equal"), 0),
        GkCard("What is the largest organ of the human body?", listOf("Skin", "Heart", "Liver"), 0),
        GkCard("What is the capital of Australia?", listOf("Canberra", "Sydney", "Melbourne"), 0),
        GkCard("A six-sided polygon is called a...?", listOf("Hexagon", "Pentagon", "Octagon"), 0),
        GkCard("What is often called the powerhouse of the cell?", listOf("Mitochondria", "Nucleus", "Ribosome"), 0),
        GkCard("Who wrote Romeo and Juliet?", listOf("Shakespeare", "Dickens", "Tolkien"), 0),
        GkCard("What is the square root of 64?", listOf("8", "6", "16"), 0),
        GkCard("Which gas do plants absorb from the air?", listOf("Carbon dioxide", "Oxygen", "Nitrogen"), 0),
        GkCard("What is the capital of Canada?", listOf("Ottawa", "Toronto", "Vancouver"), 0),
        GkCard("Which country is home to the Kangaroo?", listOf("Australia", "South Africa", "India"), 0),
        GkCard("What is the main gas found in the air we breathe?", listOf("Nitrogen", "Oxygen", "Carbon dioxide"), 0),
        GkCard("How many seconds are in one hour?", listOf("3600", "60", "120"), 0),
        GkCard("What is the name of the process when liquid turns into gas?", listOf("Evaporation", "Condensation", "Freezing"), 0),
        GkCard("Which planet is famous for its beautiful rings?", listOf("Saturn", "Uranus", "Neptune"), 0),
        GkCard("What is the square root of 121?", listOf("11", "12", "9"), 0),
        GkCard("How many degrees are in a right angle?", listOf("90", "180", "45"), 0),
        GkCard("What is the largest hot desert in the world?", listOf("Sahara", "Gobi", "Kalahari"), 0),
        GkCard("Which historical figure discovered gravity under an apple tree?", listOf("Isaac Newton", "Albert Einstein", "Galileo Galilei"), 0),
        GkCard("What is the value of Pi rounded to two decimal places?", listOf("3.14", "3.16", "3.12"), 0),
        GkCard("I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?", listOf("Echo", "Kite", "Cloud"), 0),
        GkCard("Unscramble this word to find an animal: \"P H N E T L A E\"", listOf("Elephant", "Panther", "Antelope"), 0),
        GkCard("Which is the largest ocean on Earth?", listOf("Pacific", "Atlantic", "Indian"), 0),
        // -- expansion --
        GkCard("Who wrote the Indian national anthem?", listOf("Rabindranath Tagore", "Mahatma Gandhi", "Subhas Bose"), 0),
        GkCard("Which Indian city is called the Silicon Valley of India?", listOf("Bengaluru", "Mumbai", "Chennai"), 0),
        GkCard("What is the chemical formula of water?", listOf("H₂O", "CO₂", "O₂"), 0),
        GkCard("Which organ filters blood in the human body?", listOf("Kidneys", "Stomach", "Lungs"), 0),
        GkCard("What percentage of Earth is covered by water (roughly)?", listOf("71%", "31%", "91%"), 0),
        GkCard("Which is the smallest planet in our solar system?", listOf("Mercury", "Mars", "Pluto"), 0),
        GkCard("Who invented the light bulb (commercially)?", listOf("Thomas Edison", "Isaac Newton", "Graham Bell"), 0),
        GkCard("What is 25% of 200?", listOf("50", "25", "100"), 0),
        GkCard("Which continent has the most countries?", listOf("Africa", "Asia", "Europe"), 0),
        GkCard("DNA is found in which part of the cell?", listOf("Nucleus", "Cell wall", "Membrane"), 0),
        GkCard("Which instrument measures earthquakes?", listOf("Seismograph", "Barometer", "Telescope"), 0),
        GkCard("The Statue of Liberty was a gift from which country?", listOf("France", "England", "Spain"), 0),
        GkCard("Which is the fastest bird in a dive?", listOf("Peregrine falcon", "Eagle", "Ostrich"), 0),
        GkCard("What is 2 to the power of 5?", listOf("32", "25", "64"), 0),
        GkCard("Mount Everest lies on the border of Nepal and...?", listOf("China", "India", "Bhutan"), 0),
        GkCard("Which metal is liquid at room temperature?", listOf("Mercury", "Iron", "Silver"), 0),
        GkCard("How many chambers does the human heart have?", listOf("4", "2", "6"), 0),
        GkCard("Which festival celebrates colours in India?", listOf("Holi", "Diwali", "Onam"), 0),
        GkCard("What does 'www' stand for?", listOf("World Wide Web", "World Web Wide", "Wide World Web"), 0),
        GkCard("An angle greater than 90° but less than 180° is called...?", listOf("Obtuse", "Acute", "Right"), 0),
    )
}
