# Think Like a Coder — Band C (ages 9-10)
# 4 sections x 3 units x 4 stops = 48 stops.
# Each stop: (id, title, teach_line, demo, [(shape, question, answer_hint)])
#
# Shapes: predict choose fix spot complete compare count inverse debug constrain
# Widgets: gridbot blockstack tracetable flowbranch patternstrip

SKILL = {
    "name": "Think Like a Coder",
    # Lowercase. Curriculum.kt lowercases before comparing but
    # lib/curriculum.dart did not, and 'C' (0x43) sorts below 'a' (0x61), so
    # an uppercase band made the roadmap pick Number Sense for a band-c child
    # while the gate served this skill.
    "band": "c",
    "ages": "9–10",
    "promise": "Your child will read a program, spot the bug, and think in loops "
               "and conditions — the thinking behind every game they play.",
    "weeks": "6–8",
}

# section -> (title, subtitle, units)
# unit -> (title, stops)
SECTIONS = [
("Sequences", "A program is a list of steps, and the order is the whole game.", [

 ("Order Matters", [
  ("1.1.1", "Top to bottom",
   "A program runs one line at a time, from the top down. Nothing skips ahead.",
   "Nupo walks a 3-step program while each block lights up in turn.",
   [("predict","Nupo runs UP, UP, RIGHT. Tap the tile he finishes on.","(1,2)"),
    ("choose","Which program gets Nupo to the flag?","the one ending RIGHT"),
    ("spot","Tap the instruction that runs FIRST.","top block"),
    ("count","How many instructions are in this program?","4"),
    ("predict","Same program, new start tile. Where does he land now?","shifted by start"),
    ("compare","Do these two programs end on the same tile?","no"),
    ("fix","Drag the blocks so Nupo reaches the star.","UP UP RIGHT")]),

  ("1.1.2", "Swap two steps, change everything",
   "Two programs can hold the very same instructions and still end up in different places.",
   "The same three blocks shown twice, in two orders, each running to a different tile.",
   [("compare","Same blocks, different order. Same ending tile?","no"),
    ("spot","Two programs differ by one swap. Tap the swapped block.","block 2"),
    ("predict","Where does Nupo land after this swap?","(2,1)"),
    ("choose","Which of these three orders reaches the flag?","B"),
    ("fix","Swap exactly one pair to reach the flag.","swap 2 and 3"),
    ("compare","Does swapping the LAST two steps change the ending here?","yes"),
    ("predict","Program A then program B, run back to back. Final tile?","(3,3)")]),

  ("1.1.3", "Some steps need to happen first",
   "You cannot open a door you have not walked to yet. Some steps depend on earlier ones.",
   "Nupo tries to pick up a key he has not reached; the block flashes red.",
   [("debug","This program fails. Tap the step that could not run.","PICK UP"),
    ("choose","Which order lets Nupo pick up the key AND open the door?","walk, pick, walk, open"),
    ("spot","Tap the step that must happen before OPEN DOOR.","PICK UP KEY"),
    ("fix","Reorder so the key is collected before the door.","move PICK UP earlier"),
    ("predict","Nupo has no key. What happens at OPEN DOOR?","nothing / fails"),
    ("complete","One step is missing before OPEN. Which?","PICK UP KEY"),
    ("compare","Does collecting the key later still work?","no")]),

  ("1.1.4", "Boss — order",
   None,
   None,
   [("choose","Which program collects both stars and reaches the flag?","C"),
    ("fix","Reorder five blocks to clear the level.","—"),
    ("debug","Run it. Tap the first step that goes wrong.","step 3"),
    ("predict","Where does Nupo finish?","(4,0)"),
    ("count","How many steps does the working program need?","6"),
    ("inverse","Here is the path Nupo took. Build the program.","UP RIGHT RIGHT DOWN")]),
 ]),

 ("Being Precise", [
  ("1.2.1", "A computer does exactly what you say",
   "A computer never guesses what you meant. It does exactly, only, what you wrote.",
   "Nupo walks straight into a wall because the program said so.",
   [("predict","The program says RIGHT but a wall is there. What happens?","he stops / bumps"),
    ("choose","Which program avoids the wall?","the one going around"),
    ("spot","Tap the step that walks into the wall.","step 2"),
    ("fix","Change one step to go around the wall.","RIGHT to UP"),
    ("compare","Does Nupo go around walls on his own?","no"),
    ("debug","Why did Nupo stop early?","wall at step 3"),
    ("predict","Remove the wall. Now where does he end?","(3,1)")]),

  ("1.2.2", "A missing step breaks it",
   "Leave one instruction out and the whole program misses.",
   "A four-step program with one block greyed out; the robot lands one tile short.",
   [("complete","One step is missing. Which one reaches the flag?","UP"),
    ("predict","With the step missing, where does he stop?","one short"),
    ("count","How many more steps are needed?","1"),
    ("complete","Fill the gap in the middle of this program.","RIGHT"),
    ("choose","Which missing step reaches the star, not the flag?","LEFT"),
    ("debug","Nupo ends one tile short. What is missing?","a final UP"),
    ("fix","Add the missing block and reorder.","—")]),

  ("1.2.3", "Extra steps waste moves",
   "Steps that undo each other still cost you. Shorter programs are better programs.",
   "A program with UP then DOWN highlighted as wasted.",
   [("spot","Tap the pair of steps that cancel each other out.","UP + DOWN"),
    ("count","How many steps are wasted here?","2"),
    ("choose","Which program reaches the flag in fewest steps?","B"),
    ("fix","Delete the wasted steps.","—"),
    ("count","What is the fewest steps to reach the flag?","5"),
    ("compare","Both programs work. Is one shorter?","yes, B"),
    ("constrain","Reach the flag in exactly 4 steps.","—")]),

  ("1.2.4", "Boss — precision",
   None, None,
   [("debug","Find the one step causing the crash.","step 4"),
    ("fix","Remove the waste and reach the flag.","—"),
    ("constrain","Clear the level in exactly 6 steps.","—"),
    ("complete","Two steps are missing. Fill both.","UP, RIGHT"),
    ("count","Fewest possible steps for this level?","7"),
    ("choose","Which of these four programs is both correct AND shortest?","D")]),
 ]),

 ("Reading and Writing Programs", [
  ("1.3.1", "Trace it in your head",
   "A good coder can run a program in their head before pressing play.",
   "A program steps forward one line at a time while a finger traces the grid.",
   [("predict","Do not run it. Where does Nupo end up?","(2,3)"),
    ("predict","Trace this 6-step program. Final tile?","(0,4)"),
    ("choose","Which ending tile is correct for this program?","B"),
    ("count","How many stars does this program collect?","2"),
    ("compare","Two programs, same ending tile?","yes"),
    ("predict","Halfway through, which tile is he on?","(1,1)"),
    ("debug","Your trace says the flag; running it says a wall. Where do they differ?","step 5")]),

  ("1.3.2", "From path to program",
   "Working backwards is a real skill: see the route, write the instructions.",
   "A dotted path draws itself on the grid, then blocks assemble to match it.",
   [("inverse","Here is the path. Build the program.","UP RIGHT RIGHT"),
    ("inverse","Build the program for this longer path.","6 blocks"),
    ("choose","Which program draws this path?","C"),
    ("complete","This program matches the path except one gap. Fill it.","DOWN"),
    ("inverse","Build a program that collects both stars on the way.","—"),
    ("compare","Does this program match the drawn path?","no"),
    ("count","How many turns does this path need?","3")]),

  ("1.3.3", "The shortest route",
   "Often many programs work. The best one does the job in the fewest steps.",
   "Two routes to the same flag, one clearly longer, both animating side by side.",
   [("choose","Both reach the flag. Which is shorter?","A"),
    ("count","Shortest number of steps to the flag?","6"),
    ("constrain","Reach the flag in exactly 5 steps.","—"),
    ("fix","Shorten this program without breaking it.","—"),
    ("compare","Is the shortest route always a straight line here?","no, wall"),
    ("choose","Which route collects the star AND is shortest?","B"),
    ("count","How many steps does the wall add?","2")]),

  ("1.3.4", "Boss — sequences",
   None, None,
   [("inverse","Build the program for this path.","—"),
    ("constrain","Clear the level in exactly 8 steps.","—"),
    ("debug","Find and fix the single broken step.","—"),
    ("predict","Trace it. Where does Nupo finish?","(4,4)"),
    ("count","Fewest steps to collect all three stars?","11"),
    ("choose","Which program is correct, shortest, and collects every star?","C")]),
 ]),
]),

("Loops", "When the same steps repeat, say it once and repeat it.", [

 ("Spotting Repetition", [
  ("2.1.1", "The same steps, again and again",
   "When you see the same block of steps over and over, that is a loop waiting to happen.",
   "A 9-block program collapses into a 3-block loop with a repeat arrow.",
   [("spot","Tap where the repeating part starts.","block 1"),
    ("patternstrip","Tap the part of this program that repeats.","UP RIGHT"),
    ("count","How many times does the pattern repeat?","3"),
    ("choose","Which loop matches this long program?","REPEAT 3 [UP RIGHT]"),
    ("compare","Do the long program and the loop do the same thing?","yes"),
    ("spot","Tap the FIRST step outside the repeating part.","block 7"),
    ("count","How many blocks does the loop save?","6")]),

  ("2.1.2", "Where the repeat starts and ends",
   "A loop needs a beginning and an end. Get them wrong and it repeats the wrong thing.",
   "Loop brackets slide along the program, highlighting what is inside.",
   [("spot","Tap the last step INSIDE the loop.","RIGHT"),
    ("choose","Which loop brackets are placed correctly?","B"),
    ("predict","With these brackets, where does Nupo end?","(3,0)"),
    ("fix","Move the loop end to the right place.","—"),
    ("compare","Do these two bracket placements behave the same?","no"),
    ("debug","The loop repeats one step too many. Tap it.","the extra UP"),
    ("count","How many steps run in total?","9")]),

  ("2.1.3", "Loops make programs shorter",
   "The same job, far fewer blocks. That is the whole point.",
   "Side-by-side: 12 blocks versus REPEAT 4 with 3 blocks.",
   [("count","How many blocks without a loop?","12"),
    ("count","How many with a loop?","4"),
    ("choose","Which is the shortest correct program?","C"),
    ("fix","Rewrite this program using a loop.","REPEAT 4 [...]"),
    ("compare","Same result, fewer blocks — still correct?","yes"),
    ("constrain","Reach the flag using at most 5 blocks.","loop needed"),
    ("inverse","Here is a loop. Write it out the long way.","9 blocks")]),

  ("2.1.4", "Boss — spotting loops", None, None,
   [("spot","Tap the repeating section.","—"),
    ("fix","Turn this program into a loop.","—"),
    ("count","How many blocks does the loop save?","8"),
    ("predict","Where does the looped program finish?","(4,2)"),
    ("choose","Which loop is equivalent to the long program?","B"),
    ("constrain","Clear the level in 4 blocks or fewer.","—")]),
 ]),

 ("Loop Counts", [
  ("2.2.1", "Repeat exactly N times",
   "REPEAT 4 means the steps inside run four times. Not three. Not five.",
   "A counter ticks 1,2,3,4 as the loop body runs and the robot advances.",
   [("predict","REPEAT 3 [UP]. Where does Nupo end?","3 up"),
    ("count","How many total moves does REPEAT 4 [UP RIGHT] make?","8"),
    ("choose","Which repeat count reaches the flag?","5"),
    ("complete","Fill in the repeat count.","4"),
    ("predict","REPEAT 2 [UP UP RIGHT]. Final tile?","(1,4)"),
    ("compare","Is REPEAT 2 [UP UP] the same as REPEAT 4 [UP]?","yes"),
    ("count","How many times does the body run?","6")]),

  ("2.2.2", "Off by one",
   "One repeat too many or too few is the most common bug there is.",
   "The robot overshoots the flag by exactly one tile, then rewinds.",
   [("debug","Nupo overshoots by one tile. What is the repeat count?","one too many"),
    ("fix","Change the count so he lands on the flag.","4 not 5"),
    ("predict","REPEAT 5 when 4 was needed — where does he stop?","one past"),
    ("count","Correct repeat count for this level?","6"),
    ("debug","He stops one short. What went wrong?","count too low"),
    ("choose","Which count is right — 3, 4 or 5?","4"),
    ("compare","Does one extra repeat always overshoot?","no, walls")]),

  ("2.2.3", "Choosing the count",
   "Work out how far you need to go, then set the count to match.",
   "Distance measured on the grid, then written into the repeat box.",
   [("count","The flag is 6 tiles up. Body is UP. Count?","6"),
    ("count","Body is UP UP. Flag 6 tiles up. Count?","3"),
    ("complete","Fill the count to collect all stars.","4"),
    ("choose","Body is UP RIGHT, flag is 3 up and 3 right. Count?","3"),
    ("predict","Count 3, body UP RIGHT — how many tiles travelled?","6"),
    ("constrain","Reach the flag with exactly one loop.","—"),
    ("fix","The body is right but the count is wrong. Fix it.","—")]),

  ("2.2.4", "Boss — counts", None, None,
   [("complete","Fill the missing repeat count.","5"),
    ("debug","Off by one. Fix it.","—"),
    ("count","Total moves this loop makes?","12"),
    ("constrain","Clear the level with one loop and nothing else.","—"),
    ("predict","Where does REPEAT 4 [RIGHT UP] finish?","(4,4)"),
    ("choose","Which loop clears the level?","C")]),
 ]),

 ("Loops Inside Loops", [
  ("2.3.1", "A loop inside a loop",
   "The inner loop finishes completely every single time the outer loop goes round once.",
   "An outer counter ticks once while the inner counter races 1,2,3.",
   [("predict","REPEAT 2 [ REPEAT 3 [UP] ]. How far up?","6"),
    ("count","How many times does the inner body run in total?","6"),
    ("choose","Which nested loop draws this square?","B"),
    ("spot","Tap the inner loop.","inner brackets"),
    ("predict","Outer 3, inner 2, body RIGHT. Final tile?","(6,0)"),
    ("compare","Is REPEAT 2[REPEAT 3] the same as REPEAT 6?","yes here"),
    ("count","How many times does the OUTER loop run?","2")]),

  ("2.3.2", "Counting the total",
   "Outer count times inner count. That is how many times the inside runs.",
   "A multiplication grid lights up as the loops run.",
   [("count","Outer 3, inner 4. Inner body runs how many times?","12"),
    ("count","Total moves for REPEAT 4 [ REPEAT 2 [UP RIGHT] ]?","16"),
    ("choose","Which nesting gives exactly 12 moves?","B"),
    ("complete","Fill the inner count to make 20 moves total.","5"),
    ("compare","Outer 2 inner 6 versus outer 6 inner 2 — same total?","yes"),
    ("predict","Which tile after outer 2, inner 3, body UP?","(0,6)"),
    ("count","How many stars collected in total?","8")]),

  ("2.3.3", "When nesting helps",
   "Nesting shines when a pattern repeats inside another pattern — like drawing four sides of a square.",
   "Nupo draws a square: REPEAT 4 [ forward, turn ].",
   [("choose","Which program draws the full square?","REPEAT 4 [UP RIGHT]"),
    ("fix","Rewrite this long program with nested loops.","—"),
    ("count","Blocks saved by nesting here?","14"),
    ("constrain","Draw the whole shape in 5 blocks or fewer.","—"),
    ("compare","Would a single loop work here?","no"),
    ("inverse","Here is the shape drawn. Build the nested loop.","—"),
    ("choose","Which is shortest and correct?","D")]),

  ("2.3.4", "Boss — loops", None, None,
   [("predict","Trace the nested loop. Final tile?","(6,6)"),
    ("count","Total moves?","24"),
    ("fix","Turn this 20-block program into nested loops.","—"),
    ("debug","The inner count is wrong. Fix it.","—"),
    ("constrain","Clear the level in 6 blocks.","—"),
    ("choose","Which nested loop collects every star?","A")]),
 ]),
]),

("Conditions", "Programs make decisions: do this only if that is true.", [

 ("If and Then", [
  ("3.1.1", "Only if",
   "IF checks something first. If it is not true, the steps inside are skipped entirely.",
   "Nupo walks past a star with the IF branch greyed out, then again with it lit.",
   [("flowbranch","IF star ahead THEN pick up. There is no star. What happens?","skipped"),
    ("predict","With a star ahead, how many stars does he end with?","1"),
    ("choose","Which condition picks up ONLY gold stars?","IF gold"),
    ("compare","Does the IF body always run?","no"),
    ("count","Stars collected on this route?","2"),
    ("spot","Tap the step that runs only sometimes.","inside IF"),
    ("predict","No star anywhere. Where does he finish?","same tile")]),

  ("3.1.2", "If, or else",
   "IF / ELSE gives two roads. Exactly one of them is always taken.",
   "The path forks; one branch lights green, the other greys out.",
   [("flowbranch","Wall ahead is TRUE. Which branch runs?","the ELSE"),
    ("predict","Path is clear. Where does Nupo end?","(3,0)"),
    ("choose","Which IF/ELSE gets round the wall either way?","B"),
    ("compare","Can both branches run at once?","no"),
    ("complete","Fill the ELSE branch so he never crashes.","GO UP"),
    ("predict","Wall present. Final tile?","(0,3)"),
    ("debug","He crashes when the wall is there. What is missing?","ELSE")]),

  ("3.1.3", "Conditions inside loops",
   "Put an IF inside a loop and the check happens on every single pass.",
   "A loop runs four times; the IF fires on only two of them.",
   [("count","REPEAT 4 with IF star. Two tiles have stars. Stars collected?","2"),
    ("predict","How many times is the condition CHECKED?","4"),
    ("choose","Which program collects only the stars, skipping rocks?","C"),
    ("count","How many times does the IF body run?","2"),
    ("compare","Checked four times, run twice — is that right?","yes"),
    ("debug","It picks up rocks too. Fix the condition.","—"),
    ("predict","No stars on the route. Ending tile?","(4,0)")]),

  ("3.1.4", "Boss — if/then", None, None,
   [("flowbranch","Trace both branches. Which runs?","—"),
    ("count","Stars collected?","3"),
    ("fix","Add an IF so he avoids the water.","—"),
    ("predict","Final tile with the wall present?","(2,4)"),
    ("choose","Which program works whether or not the door is locked?","B"),
    ("debug","Find the condition that never fires.","—")]),
 ]),

 ("What the check looks at", [
  ("3.2.1", "The square under his feet",
   "A check only ever looks at where Nupo is standing, or at the square right next to him.",
   "Nupo stands on a star; the check lights up. He steps off it and the same check goes dark.",
   [("compare","'Wall ahead' with a clear path. True or false?","false"),
    ("compare","'Star on this tile' standing on a star. True or false?","true"),
    ("choose","Which of these is a condition?","'is wall ahead'"),
    ("predict","Condition false — does the body run?","no"),
    ("compare","'Nupo has 3 keys' when he has 3. True?","true"),
    ("spot","Tap the condition in this program.","the IF chip"),
    ("compare","Can a condition be both true and false?","no")]),

  ("3.2.2", "Blocked or clear",
   "A wall check asks whether the next square is free. The edge of the board counts as a wall too.",
   "Nupo meets a wall; the IF road turns him, and the OR ELSE road greys out.",
   [("compare","Nupo has 3 coins, needs more than 5. True?","false"),
    ("compare","Coins = 7, condition 'coins > 5'. True?","true"),
    ("choose","Which condition means 'exactly 4'?","coins = 4"),
    ("predict","Coins 5, condition 'coins > 5'. Does the body run?","no"),
    ("complete","Fill the condition so it fires at 10 or more.","coins >= 10"),
    ("compare","'coins < 3' with 3 coins. True?","false"),
    ("count","How many of these five conditions are true?","2")]),

  ("3.2.3", "Not",
   "NOT reads the same check backwards. 'Is the way up blocked' becomes 'is the way up clear'.",
   "The same board runs twice: once on IF WALL ABOVE, once on IF NOT WALL ABOVE, and he goes opposite ways.",
   [("compare","'NOT wall ahead' with a wall. True?","false"),
    ("choose","Which means 'the tile is empty'?","NOT star"),
    ("predict","IF NOT wall THEN move — wall present. Does he move?","no"),
    ("compare","NOT (NOT true). What is it?","true"),
    ("complete","Fill in a condition meaning 'no key held'.","NOT has key"),
    ("compare","'NOT coins > 5' with 6 coins. True?","false"),
    ("fix","Rewrite this IF using NOT so it is shorter.","—")]),

  ("3.2.4", "Boss — checks", None, None,
   [("compare","Five conditions. How many are true?","3"),
    ("predict","Which branch runs given these values?","ELSE"),
    ("complete","Fill the condition to fire at exactly 8.","= 8"),
    ("choose","Which condition means 'not empty'?","NOT empty"),
    ("debug","This condition is always false. Why?","—"),
    ("compare","NOT(coins < 4) with 4 coins. True?","true")]),
 ]),

 ("Both, and either", [
  ("3.3.1", "Both must be true",
   "Put a check inside a check and the step only happens when both of them say yes.",
   "Nupo walks a row of stars and picks up only the ones with a wall above them.",
   [("compare","Has key TRUE, door ahead TRUE. 'key AND door'?","true"),
    ("compare","Has key TRUE, door ahead FALSE. 'key AND door'?","false"),
    ("choose","Which condition opens the door only when both are met?","A"),
    ("predict","Only one is true. Does the body run?","no"),
    ("count","Of these four AND conditions, how many are true?","1"),
    ("complete","Fill in: open only with a key AND enough coins.","—"),
    ("compare","Both false. 'A AND B'?","false")]),

  ("3.3.2", "Either will do",
   "Two roads that end at the same step. Either check can send him down its road, so one is enough.",
   "The same step sits at the end of the IF road and the OR ELSE road; whichever check fires, he takes it.",
   [("compare","Key TRUE, coins FALSE. 'key OR coins'?","true"),
    ("compare","Both false. 'A OR B'?","false"),
    ("choose","Which means 'a star or a coin'?","B"),
    ("predict","One condition true. Does the body run?","yes"),
    ("compare","Both true. 'A OR B'?","true"),
    ("count","How many of these OR conditions are true?","3"),
    ("choose","AND or OR — which fires more often?","OR")]),

  ("3.3.3", "Putting them together",
   "Real programs use both: a step guarded by two checks, and a step two different checks can reach.",
   "One board, run twice: once with the checks nested, once with them side by side, ending differently.",
   [("compare","(key AND door) OR bridge — only bridge true. Result?","true"),
    ("choose","Which condition lets him pass by key or by bridge?","C"),
    ("predict","Which branch runs with these three values?","THEN"),
    ("complete","Fill in so he passes with a key, or with 10 coins.","OR"),
    ("compare","NOT (A AND B) with both true. Result?","false"),
    ("count","How many combinations make this true?","3"),
    ("fix","Swap the AND for an OR and predict the change.","—")]),

  ("3.3.4", "Boss — both and either", None, None,
   [("compare","Evaluate this three-part condition.","true"),
    ("choose","Which condition clears the level every time?","D"),
    ("predict","Trace the branch taken.","ELSE"),
    ("complete","Fill both blanks in the condition.","AND, NOT"),
    ("debug","This condition never fires. Why?","impossible AND"),
    ("count","How many of eight cases are true?","5")]),
 ]),
]),

("Debugging", "Programs go wrong. Finding out why is the real skill.", [

 ("Finding Bugs", [
  ("4.1.1", "Run it and watch",
   "The fastest way to find a bug is to run the program and watch where it stops matching your plan.",
   "The robot runs, hits a wall, and the offending block flashes red.",
   [("debug","Run it. Tap the step where it goes wrong.","step 3"),
    ("predict","Before running: where SHOULD it end?","(3,3)"),
    ("compare","Where it actually ends versus where it should — same?","no"),
    ("spot","Tap the first block that behaves unexpectedly.","block 3"),
    ("fix","Change that one block to fix it.","RIGHT to UP"),
    ("debug","It crashes at the wall. Which step causes it?","step 5"),
    ("count","How many steps ran before it broke?","4")]),

  ("4.1.2", "The FIRST wrong step",
   "Once one step is wrong, everything after it looks wrong too. Find the first one.",
   "Two paths diverge at one point, the split highlighted.",
   [("spot","Both paths go wrong. Tap where they FIRST differ.","step 4"),
    ("debug","Steps 4,5,6 all look wrong. Which is the real bug?","step 4"),
    ("predict","Fix step 4 only. Does the rest work?","yes"),
    ("choose","Which single change fixes everything after it?","B"),
    ("spot","Tap the earliest broken step.","step 2"),
    ("count","How many steps were correct before the bug?","3"),
    ("fix","Fix only the first wrong step.","—")]),

  ("4.1.3", "Predict, then check",
   "Say what you think will happen before you press play. When you are wrong, you have found the bug.",
   "A prediction is placed on a tile, then the run shows a different tile.",
   [("predict","Where do you think it ends? Tap a tile.","(2,2)"),
    ("compare","Your prediction versus the run — do they match?","no"),
    ("debug","They differ at step 5. What went wrong there?","wrong direction"),
    ("predict","Now predict again after the fix.","(3,3)"),
    ("compare","Do they match now?","yes"),
    ("choose","Which prediction is correct for this program?","C"),
    ("debug","Prediction and run differ from step 1. What is wrong?","wrong start")]),

  ("4.1.4", "Boss — debugging", None, None,
   [("debug","Find the first wrong step.","step 3"),
    ("fix","Fix it with one change.","—"),
    ("predict","After the fix, final tile?","(4,4)"),
    ("debug","There are two bugs. Tap the earlier one.","step 2"),
    ("count","How many steps run correctly before the bug?","1"),
    ("choose","Which fix works for BOTH bugs?","B")]),
 ]),

 ("Variables", [
  ("4.2.1", "A box that holds a number",
   "A variable is a labelled box. You can look in it, and you can change what is inside.",
   "A box labelled COINS shows 0, then 1, then 2 as stars are collected.",
   [("tracetable","COINS starts at 0. Nupo collects 3 stars. COINS now?","3"),
    ("predict","After this program, what is in COINS?","5"),
    ("choose","Which step changes the value in the box?","ADD 1"),
    ("count","How many times does COINS change?","4"),
    ("compare","Does reading COINS change it?","no"),
    ("complete","Fill in the starting value.","0"),
    ("tracetable","Trace COINS through five steps.","2")]),

  ("4.2.2", "Changing what is inside",
   "SET puts a new value in. ADD changes the value that is already there.",
   "SET replaces the number; ADD stacks onto it, shown side by side.",
   [("compare","COINS = 5, then SET COINS 2. Value?","2"),
    ("compare","COINS = 5, then ADD 2. Value?","7"),
    ("choose","Which step doubles the coins?","—"),
    ("predict","SET 3, ADD 4, ADD 1. Final value?","8"),
    ("debug","It should be 6 but shows 2. Which step is wrong?","the SET"),
    ("complete","Fill in the step that makes it 10.","ADD 4"),
    ("tracetable","Trace the box through the whole program.","9")]),

  ("4.2.3", "Tracing state",
   "To understand a program, keep a little table of what is in every box at every step.",
   "A trace table fills in row by row as the program steps.",
   [("tracetable","Fill the missing row of the trace table.","4"),
    ("predict","What is COINS at step 6?","7"),
    ("tracetable","Two boxes now. Trace both.","3, 5"),
    ("debug","The table and the run disagree at step 4. Why?","—"),
    ("count","How many steps until COINS reaches 10?","5"),
    ("compare","Do COINS and KEYS ever hold the same value?","yes, step 3"),
    ("predict","Final values of both boxes?","8 and 2")]),

  ("4.2.4", "Boss — variables", None, None,
   [("tracetable","Complete the trace table.","—"),
    ("predict","Final value of COINS?","12"),
    ("debug","Find the step that sets the wrong value.","step 4"),
    ("complete","Fill the step needed to reach exactly 20.","ADD 8"),
    ("count","How many times does the value change inside the loop?","4"),
    ("compare","Is the final value the same if the loop runs one fewer time?","no")]),
 ]),

 ("Breaking It Down", [
  ("4.3.1", "One big problem, small parts",
   "Big problems are just small problems stacked up. Solve them one at a time.",
   "A long level splits visually into three lit segments, solved one by one.",
   [("choose","Which part should you solve FIRST?","reach the key"),
    ("spot","Tap the section of the level that gets the key.","left third"),
    ("count","How many separate parts does this level have?","3"),
    ("fix","Build just the first part.","—"),
    ("choose","Which order of the three parts works?","B"),
    ("predict","Solve part 1 only. Where does he stop?","(2,0)"),
    ("fix","Now join all three parts into one program.","—")]),

  ("4.3.2", "Naming a chunk you reuse",
   "If you use the same group of steps again and again, give it a name and just call the name.",
   "Three identical block groups collapse into one named CLIMB block, used three times.",
   [("spot","Tap the chunk that appears three times.","UP UP RIGHT"),
    ("choose","Which named chunk matches?","CLIMB"),
    ("count","Blocks saved by naming this chunk?","6"),
    ("predict","CLIMB, CLIMB, CLIMB — where does he end?","(3,6)"),
    ("fix","Replace the repeats with the named chunk.","—"),
    ("compare","Is a named chunk the same as a loop?","not quite"),
    ("constrain","Clear the level using CLIMB exactly twice.","—")]),

  ("4.3.3", "Putting it all together",
   "Sequences, loops, conditions and variables — real programs use all four at once.",
   "A full level runs end to end using every idea from the skill.",
   [("predict","Trace this full program. Final tile?","(5,5)"),
    ("count","Total coins collected?","9"),
    ("debug","One bug remains. Find it.","the loop count"),
    ("fix","Fix it and clear the level.","—"),
    ("choose","Which program uses a loop AND a condition correctly?","C"),
    ("constrain","Clear it in 10 blocks or fewer.","—"),
    ("tracetable","Trace COINS to the end.","9")]),

  ("4.3.4", "Boss — the whole skill", None, None,
   [("predict","Trace a program using loops, conditions and a variable.","(6,4)"),
    ("debug","Two bugs. Find the first.","—"),
    ("fix","Fix both and clear the level.","—"),
    ("constrain","Clear the final level in 12 blocks.","—"),
    ("count","Final value of COINS?","15"),
    ("choose","Which of these four programs clears every level?","D"),
    ("inverse","Build the program for this path from scratch.","—")]),
 ]),
]),
]

# One free hint per question. Never the answer — it names the METHOD, then
# points at where in THIS question to apply it. Examples across four shapes so
# the authoring pattern is clear.
HINTS = [
 ("1.1.1", "predict", "Nupo runs UP, UP, RIGHT. Tap the tile he finishes on.",
  "Take the instructions one at a time from the top, moving your finger a tile "
  "each time. Two of them say the same thing."),
 ("2.2.2", "debug", "Nupo overshoots by one tile. What is the repeat count?",
  "Count the tiles between Nupo and the flag, then count what the loop body "
  "moves him each pass. Compare the two."),
 ("3.3.1", "compare", "Has key TRUE, door ahead FALSE. 'key AND door'?",
  "AND needs both sides true. Check each side on its own first, then decide."),
 ("4.2.3", "tracetable", "Fill the missing row of the trace table.",
  "Look at the row above it and at the single step between them. Only that one "
  "step can have changed the box."),
]

# Rules for writing a hint.
HINT_RULES = [
 "Name the method first — how you attack this SHAPE of question.",
 "Then point at where in this question to start, never at the answer.",
 "Never state a result, a tile, a count or a true/false.",
 "One or two sentences. A child wanting their game will not read three.",
 "Written per question, not per stop — the same idea needs a different nudge "
 "in a predict than in an inverse.",
]

WIDGETS = [
 ("gridbot", "The workhorse. A grid, Nupo, walls, stars, a flag, and a program that runs.",
  "~60% of stops",
  '{"visual":"gridbot","grid":[5,5],"start":[0,0],"goal":[4,2],\n'
  ' "walls":[[2,0],[2,1]],"stars":[[1,1],[3,2]],\n'
  ' "program":["up","up","right","right"],\n'
  ' "interaction":"run_and_watch|tap_cell|drag_blocks",\n'
  ' "answer":{"type":"cell","value":[4,2]}}'),
 ("blockstack", "Instruction blocks to order, complete or trim. Often paired with gridbot.",
  "ordering, fixing, completing",
  '{"visual":"blockstack","blocks":["up","right","up"],\n'
  ' "slots":4,"locked":[0],"interaction":"drag",\n'
  ' "answer":{"type":"order","value":["up","up","right"]}}'),
 ("tracetable", "A step-by-step table of variable values. Used across the Variables unit.",
  "variables, state",
  '{"visual":"tracetable","vars":["coins","keys"],\n'
  ' "steps":[["set",0],["add",3],["add",2]],\n'
  ' "blank":[2,0],"answer":{"type":"number","value":5}}'),
 ("flowbranch", "An if/else fork with two visible paths, one of which lights up.",
  "conditions",
  '{"visual":"flowbranch","condition":"wall_ahead",\n'
  ' "value":true,"then":["turn"],"else":["forward"],\n'
  ' "answer":{"type":"branch","value":"then"}}'),
 ("patternstrip", "A long run of blocks where the repeating section must be found.",
  "spotting loops",
  '{"visual":"patternstrip","blocks":["up","right","up","right","up","right"],\n'
  ' "interaction":"select_range",\n'
  ' "answer":{"type":"range","value":[0,1]}}'),
]
